/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.pcc.marc.schema.marccallbackservice_1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-11-03T12:13:21.042+01:00
 * Generated source version: 2.4.6
 * 
 */
/*@WebServiceClient(name = "MarcCallbackService", 
                  wsdlLocation = "file:/D:/workarea/csi/siac/fase19/documentazione/INTEGRAZIONE%20PCC%2021102015/Interfacce%20WS/MarcCallbackService.wsdl",
                  targetNamespace = "http://www.csi.it/marc/schema/MarcCallbackService-1.0") 
*/public class MarcCallbackService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.csi.it/marc/schema/MarcCallbackService-1.0", "MarcCallbackService");
    public final static QName MarcCallbackServiceSOAP = new QName("http://www.csi.it/marc/schema/MarcCallbackService-1.0", "MarcCallbackServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/workarea/csi/siac/fase19/documentazione/INTEGRAZIONE%20PCC%2021102015/Interfacce%20WS/MarcCallbackService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MarcCallbackService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/workarea/csi/siac/fase19/documentazione/INTEGRAZIONE%20PCC%2021102015/Interfacce%20WS/MarcCallbackService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MarcCallbackService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MarcCallbackService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarcCallbackService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public MarcCallbackService_Service(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public MarcCallbackService_Service(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public MarcCallbackService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns MarcCallbackService
     */
    @WebEndpoint(name = "MarcCallbackServiceSOAP")
    public MarcCallbackService getMarcCallbackServiceSOAP() {
        return super.getPort(MarcCallbackServiceSOAP, MarcCallbackService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarcCallbackService
     */
    @WebEndpoint(name = "MarcCallbackServiceSOAP")
    public MarcCallbackService getMarcCallbackServiceSOAP(WebServiceFeature... features) {
        return super.getPort(MarcCallbackServiceSOAP, MarcCallbackService.class, features);
    }

}
