/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.siac.pcc.marc.schema.marccallbackservice_1_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-11-03T12:13:20.999+01:00
 * Generated source version: 2.4.6
 * 
 */
public final class MarcCallbackService_MarcCallbackServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.csi.it/marc/schema/MarcCallbackService-1.0", "MarcCallbackService");

    private MarcCallbackService_MarcCallbackServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MarcCallbackService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MarcCallbackService_Service ss = new MarcCallbackService_Service(wsdlURL, SERVICE_NAME);
        MarcCallbackService port = ss.getMarcCallbackServiceSOAP();  
        
        {
        System.out.println("Invoking aggiornamentoStatoRichiesta...");
        it.csi.siac.pcc.marc.schema.callbackservicetypes_1.AggiornamentoStatoRichiestaRequest _aggiornamentoStatoRichiesta_parameters = null;
        it.csi.siac.pcc.marc.schema.marccommontypes_1.ResponseType _aggiornamentoStatoRichiesta__return = port.aggiornamentoStatoRichiesta(_aggiornamentoStatoRichiesta_parameters);
        System.out.println("aggiornamentoStatoRichiesta.result=" + _aggiornamentoStatoRichiesta__return);


        }

        System.exit(0);
    }

}
