/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.csi.siac.pcc.marc.schema.marccallbackservice_1_0;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-11-03T12:13:21.020+01:00
 * Generated source version: 2.4.6
 * 
 */

/*@javax.jws.WebService(
                      serviceName = "MarcCallbackService",
                      portName = "MarcCallbackServiceSOAP",
                      targetNamespace = "http://www.csi.it/marc/schema/MarcCallbackService-1.0",
                      wsdlLocation = "file:/D:/workarea/csi/siac/fase19/documentazione/INTEGRAZIONE%20PCC%2021102015/Interfacce%20WS/MarcCallbackService.wsdl",
                      endpointInterface = "it.csi.marc.schema.marccallbackservice_1_0.MarcCallbackService")
                      
*/public class MarcCallbackServiceImpl implements MarcCallbackService {

    private static final Logger LOG = Logger.getLogger(MarcCallbackServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.marc.schema.marccallbackservice_1_0.MarcCallbackService#aggiornamentoStatoRichiesta(it.csi.marc.schema.callbackservicetypes_1.AggiornamentoStatoRichiestaRequest  parameters )*
     */
    public it.csi.siac.pcc.marc.schema.marccommontypes_1.ResponseType aggiornamentoStatoRichiesta(it.csi.siac.pcc.marc.schema.callbackservicetypes_1.AggiornamentoStatoRichiestaRequest parameters) { 
        LOG.info("Executing operation aggiornamentoStatoRichiesta");
        System.out.println(parameters);
        try {
            it.csi.siac.pcc.marc.schema.marccommontypes_1.ResponseType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
