/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

package it.tesoro.fatture;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FattureWS", targetNamespace = "http://www.tesoro.it/fatture", wsdlLocation = "file:/C:/workarea/csi/siac/faseX/MARC%20interfacce/wsdl/FattureWS%20xsd-wsdl%20v3.0/PCC_WSFATT.wsdl")
public class FattureWS_Service
    extends Service
{

    private final static URL FATTUREWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.tesoro.fatture.FattureWS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.tesoro.fatture.FattureWS_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/workarea/csi/siac/faseX/MARC%20interfacce/wsdl/FattureWS%20xsd-wsdl%20v3.0/PCC_WSFATT.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workarea/csi/siac/faseX/MARC%20interfacce/wsdl/FattureWS%20xsd-wsdl%20v3.0/PCC_WSFATT.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FATTUREWS_WSDL_LOCATION = url;
    }

    public FattureWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FattureWS_Service() {
        super(FATTUREWS_WSDL_LOCATION, new QName("http://www.tesoro.it/fatture", "FattureWS"));
    }

    /**
     * 
     * @return
     *     returns FattureWS
     */
    @WebEndpoint(name = "FattureWSSOAP11Port")
    public FattureWS getFattureWSSOAP11Port() {
        return super.getPort(new QName("http://www.tesoro.it/fatture", "FattureWSSOAP11Port"), FattureWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FattureWS
     */
    @WebEndpoint(name = "FattureWSSOAP11Port")
    public FattureWS getFattureWSSOAP11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tesoro.it/fatture", "FattureWSSOAP11Port"), FattureWS.class, features);
    }

}
