/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.fel.eis.feltobilancio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import it.csi.fel.eis.types.ResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FelToBilancio", targetNamespace = "http://www.csi.it/fel/eis/FelToBilancio")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.csi.fel.eis.types.ObjectFactory.class,
    it.csi.fel.eis.feltobilancio.ObjectFactory.class
})
public interface FelToBilancio {


    /**
     * 
     * @param parameters
     * @return
     *     returns it.csi.fel.eis.types.ResponseType
     */
    @WebMethod(operationName = "EsitoFatturaAttiva", action = "http://www.csi.it/fel/eis/FelToBilancio/EsitoFatturaAttiva")
    @WebResult(name = "EsitoFatturaAttivaResponse", targetNamespace = "http://www.csi.it/fel/eis/FelToBilancio", partName = "parameters")
    public ResponseType esitoFatturaAttiva(
        @WebParam(name = "EsitoFatturaAttivaRequest", targetNamespace = "http://www.csi.it/fel/eis/FelToBilancio", partName = "parameters")
        EsitoFatturaAttivaRequest parameters);

}
