/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.appjwebsrv.business;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Thu Jan 19 12:02:26 CET 2017
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://business.appjwebsrv.csi.it/", name = "WSInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WSInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "verificaEvasione", targetNamespace = "http://business.appjwebsrv.csi.it/", className = "it.csi.appjwebsrv.business.VerificaEvasione")
    @WebMethod
    @ResponseWrapper(localName = "verificaEvasioneResponse", targetNamespace = "http://business.appjwebsrv.csi.it/", className = "it.csi.appjwebsrv.business.VerificaEvasioneResponse")
    public it.csi.appjwebsrv.business.EsitoServizio verificaEvasione(
        @WebParam(name = "evasioni", targetNamespace = "")
        it.csi.appjwebsrv.business.Evasioni evasioni
    );
}
