/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.srvpers.rapws.interfaccecxf.services.missioni;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-01-22T12:53:03.426+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", name = "IMissioniService")
@XmlSeeAlso({ObjectFactory.class})
public interface IMissioniService {

    @WebResult(name = "missioneDataTypeList", targetNamespace = "")
    @RequestWrapper(localName = "vm140", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.Vm140")
    @WebMethod
    @ResponseWrapper(localName = "vm140Response", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.Vm140Response")
    public java.util.List<it.csi.srvpers.rapws.interfaccecxf.services.missioni.MissioneContabileType> vm140() throws MissioniFaultException;

    @RequestWrapper(localName = "insMD060", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.InsMD060")
    @WebMethod
    @ResponseWrapper(localName = "insMD060Response", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.InsMD060Response")
    public void insMD060(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.srvpers.rapws.interfaccecxf.services.missioni.InsMD060Type arg0
    ) throws MissioniFaultException;

    @WebResult(name = "missioneConsuntivoType", targetNamespace = "")
    @RequestWrapper(localName = "vm160", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.Vm160")
    @WebMethod
    @ResponseWrapper(localName = "vm160Response", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.Vm160Response")
    public java.util.List<it.csi.srvpers.rapws.interfaccecxf.services.missioni.MissioneConsuntivoType> vm160() throws MissioniFaultException;

    @WebResult(name = "missioneDataTypeList", targetNamespace = "")
    @RequestWrapper(localName = "viDipendentiMatr", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.ViDipendentiMatr")
    @WebMethod
    @ResponseWrapper(localName = "viDipendentiMatrResponse", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.ViDipendentiMatrResponse")
    public java.util.List<it.csi.srvpers.rapws.interfaccecxf.services.missioni.MissioneDataType> viDipendentiMatr(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws MissioniFaultException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isAlive", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.IsAlive")
    @WebMethod
    @ResponseWrapper(localName = "isAliveResponse", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.IsAliveResponse")
    public java.lang.String isAlive(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws MissioniFaultException;

    @WebResult(name = "missioneDataTypeList", targetNamespace = "")
    @RequestWrapper(localName = "viDipendentiCogn", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.ViDipendentiCogn")
    @WebMethod
    @ResponseWrapper(localName = "viDipendentiCognResponse", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.ViDipendentiCognResponse")
    public java.util.List<it.csi.srvpers.rapws.interfaccecxf.services.missioni.MissioneDataType> viDipendentiCogn(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws MissioniFaultException;

    @RequestWrapper(localName = "updMissioni", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.UpdMissioni")
    @WebMethod
    @ResponseWrapper(localName = "updMissioniResponse", targetNamespace = "http://missioni.services.interfaccecxf.rapws.srvpers.csi.it/", className = "it.csi.srvpers.rapws.interfaccecxf.services.missioni.UpdMissioniResponse")
    public void updMissioni(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws MissioniFaultException;
}
