/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.fel.eis.bilanciotofel;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BilancioToFel", targetNamespace = "http://www.csi.it/fel/eis/bilancioToFel", wsdlLocation = "http://dev-jb1fel.bilancio.csi.it:8121/http-router/webservices/bilancioToFelService?wsdl")
public class BilancioToFel_Service
    extends Service
{

    private final static URL BILANCIOTOFEL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.csi.fel.eis.bilanciotofel.BilancioToFel_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.csi.fel.eis.bilanciotofel.BilancioToFel_Service.class.getResource(".");
            url = new URL(baseUrl, "http://dev-jb1fel.bilancio.csi.it:8121/http-router/webservices/bilancioToFelService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://dev-jb1fel.bilancio.csi.it:8121/http-router/webservices/bilancioToFelService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BILANCIOTOFEL_WSDL_LOCATION = url;
    }

    public BilancioToFel_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BilancioToFel_Service() {
        super(BILANCIOTOFEL_WSDL_LOCATION, new QName("http://www.csi.it/fel/eis/bilancioToFel", "BilancioToFel"));
    }

    /**
     * 
     * @return
     *     returns BilancioToFel
     */
    @WebEndpoint(name = "BilancioToFelSOAP")
    public BilancioToFel getBilancioToFelSOAP() {
        return super.getPort(new QName("http://www.csi.it/fel/eis/bilancioToFel", "BilancioToFelSOAP"), BilancioToFel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BilancioToFel
     */
    @WebEndpoint(name = "BilancioToFelSOAP")
    public BilancioToFel getBilancioToFelSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.csi.it/fel/eis/bilancioToFel", "BilancioToFelSOAP"), BilancioToFel.class, features);
    }

}
