/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.fel.eis.bilanciotofel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import it.csi.fel.eis.bilanciotofel.types.InvioFatturaAttivaRequest;
import it.csi.fel.eis.types.ResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BilancioToFel", targetNamespace = "http://www.csi.it/fel/eis/bilancioToFel")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.csi.fel.eis.types.ObjectFactory.class,
    it.csi.fel.eis.bilanciotofel.types.ObjectFactory.class
})
public interface BilancioToFel {


    /**
     * 
     * @param parameters0
     * @param parameters
     */
    @WebMethod(operationName = "InvioFatturaAttiva", action = "http://www.csi.it/fel/eis/BilancioToFel/InvioFatturaAttiva")
    public void invioFatturaAttiva(
        @WebParam(name = "InvioFatturaAttivaRequest", targetNamespace = "http://www.csi.it/fel/eis/bilancioToFel/types", partName = "parameters")
        InvioFatturaAttivaRequest parameters,
        @WebParam(name = "InvioFatturaAttivaResponse", targetNamespace = "http://www.csi.it/fel/eis/bilancioToFel/types", mode = WebParam.Mode.OUT, partName = "parameters")
        Holder<ResponseType> parameters0);

}
