/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.pcc.marc.services.webservices_1_0;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-11-03T15:32:08.145+01:00
 * Generated source version: 2.4.6
 * 
 */
/*@WebServiceClient(name = "MarcSOAPService", 
                  wsdlLocation = "file:/D:/workarea/csi/siac/fase19/documentazione/INTEGRAZIONE%20PCC%2021102015/Interfacce%20WSNew/MarcServices.wsdl",
                  targetNamespace = "http://www.csi.it/marc/services/webservices-1.0") 
*/public class MarcSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.csi.it/marc/services/webservices-1.0", "MarcProxyService");
    public final static QName MarcSOAP = new QName("http://www.csi.it/marc/services/webservices-1.0", "MarcProxyServiceHttpSoap11Endpoint");
    static {
        URL url = null;
        try {
            //url = new URL("file:/D:/workarea/csi/siac/fase19/documentazione/INTEGRAZIONE%20PCC%2021102015/Interfacce%20WSNew/MarcServices.wsdl");
            url = new URL("http://tst-srv-marc.bilancio.csi.it/wso004/services/MarcProxyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MarcSOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/workarea/csi/siac/fase19/documentazione/INTEGRAZIONE%20PCC%2021102015/Interfacce%20WSNew/MarcServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MarcSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MarcSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarcSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public MarcSOAPService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public MarcSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public MarcSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns MarcWSPortType
     */
    @WebEndpoint(name = "MarcSOAP")
    public MarcWSPortType getMarcSOAP() {
        return super.getPort(MarcSOAP, MarcWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarcWSPortType
     */
    @WebEndpoint(name = "MarcSOAP")
    public MarcWSPortType getMarcSOAP(WebServiceFeature... features) {
        return super.getPort(MarcSOAP, MarcWSPortType.class, features);
    }

}
