/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.csi.siac.pcc.marc.services.webservices_1_0;

import java.util.logging.Logger;

import it.csi.siac.pcc.marc.schema.marccommontypes_1.ResultType;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-11-03T15:32:08.112+01:00
 * Generated source version: 2.4.6
 * 
 */

/*@javax.jws.WebService(
                      serviceName = "MarcSOAPService",
                      portName = "MarcSOAP",
                      targetNamespace = "http://www.csi.it/marc/services/webservices-1.0",
                      wsdlLocation = "file:/D:/workarea/csi/siac/fase19/documentazione/INTEGRAZIONE%20PCC%2021102015/Interfacce%20WSNew/MarcServices.wsdl",
                      endpointInterface = "it.csi.marc.services.webservices_1_0.MarcWSPortType")
                      
*/public class MarcWSPortTypeImpl implements MarcWSPortType {

    private static final Logger LOG = Logger.getLogger(MarcWSPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see it.csi.marc.services.webservices_1_0.MarcWSPortType#invioOperazioneContabile(it.tesoro.fatture.ProxyOperazioneContabileRichiestaTipo  datiRichiestaOperazioneContabile )*
     */
    public ResultType invioOperazioneContabile(it.tesoro.fatture.ProxyOperazioneContabileRichiestaTipo datiRichiestaOperazioneContabile) { 
        LOG.info("Executing operation invioOperazioneContabile");
        System.out.println(datiRichiestaOperazioneContabile);
        try {
            return null;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
