/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 03:03:54 PM CET 
//


package it.csi.siac.sirfelser.frontend.webservice.msg.inviofatturapa.services.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NaturaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NaturaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="N1"/>
 *     &lt;enumeration value="N2"/>
 *     &lt;enumeration value="N3"/>
 *     &lt;enumeration value="N4"/>
 *     &lt;enumeration value="N5"/>
 *     &lt;enumeration value="N6"/>
 *     &lt;enumeration value="N7"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NaturaType")
@XmlEnum
public enum NaturaType {


    /**
     * Escluse ex. art. 15
     * 
     */
    @XmlEnumValue("N1")
    N_1("N1"),

    /**
     * Non soggette
     * 
     */
//    @XmlEnumValue("N2")
//    N_2("N2"),

    /**
     * Non Imponibili
     * 
     */
//    @XmlEnumValue("N3")
//    N_3("N3"),

    /**
     * Esenti
     * 
     */
    @XmlEnumValue("N4")
    N_4("N4"),

    /**
     * Regime del margine
     * 
     */
    @XmlEnumValue("N5")
    N_5("N5"),

    /**
     * Inversione contabile (reverse charge)
     * 
     */
//    @XmlEnumValue("N6")
//    N_6("N6"),

    /**
     * IVA assolta in altro stato UE (vendite a distanza ex art. 40 commi 3 e 4 e art. 41 comma 1 lett. b, DL 331/93; prestazione di servizi di telecomunicazioni, tele-radiodiffusione ed elettronici ex art. 7-sexies lett. f, g, DPR 633/72 e art. 74-sexies, DPR 633/72)
     * 
     */
    @XmlEnumValue("N7")
    N_7("N7"),
    /**
     * SIAC-7557
     * Inseriti i valori: N2.1, N2.2, N3.1, N3.2, N3.3, N3.4, N3.5, N3.6, N6.1, N6.2, N6.3, N6.4, N6.5, N6.6, N6.7, N6.8, N6.9. 
	 *(i codici N2, N3 e N6 non saranno più validi a partire dal primo gennaio 2021) 
     */
    @XmlEnumValue("N2.1")
    N_2_1("N2.1"),
    @XmlEnumValue("N2.2")
    N_2_2("N2.2"),
    @XmlEnumValue("N3.1")
    N_3_1("N3.1"),
    @XmlEnumValue("N3.2")
    N_3_2("N3.2"),
    @XmlEnumValue("N3.3")
    N_3_3("N3.3"),
    @XmlEnumValue("N3.4")
    N_3_4("N3.4"),
    @XmlEnumValue("N3.5")
    N_3_5("N3.5"),
    @XmlEnumValue("N3.6")
    N_3_6("N3.6"),
    @XmlEnumValue("N6.1")
    N_6_1("N6.1"),
    @XmlEnumValue("N6.2")
    N_6_2("N6.2"),
    @XmlEnumValue("N6.3")
    N_6_3("N6.3"),
    @XmlEnumValue("N6.4")
    N_6_4("N6.4"),
    @XmlEnumValue("N6.5")
    N_6_5("N6.5"),
    @XmlEnumValue("N6.6")
    N_6_6("N6.6"),
    @XmlEnumValue("N6.7")
    N_6_7("N6.7"),
    @XmlEnumValue("N6.8")
    N_6_8("N6.8"),
    @XmlEnumValue("N6.9")
    N_6_9("N6.9")
    ;
    
    
    ;
    private final String value;

    NaturaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NaturaType fromValue(String v) {
        for (NaturaType c: NaturaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
