/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 03:03:54 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2")
package it.csi.siac.sirfelser.frontend.webservice.msg.inviofatturapa.services.model;
