/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.epay.epaywso.riconciliazione_versamenti_psp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2018-08-02T12:53:24.103+02:00
 * Generated source version: 2.4.9
 * 
 */
@WebService(targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp", name = "EPayRiconciliazioneVersamentiPSP")
@XmlSeeAlso({it.csi.epay.epaywso.riconciliazione_versamenti_psp.types.ObjectFactory.class, it.csi.epay.epaywso.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EPayRiconciliazioneVersamentiPSP { 

    @WebResult(name = "TrasmettiFlussiInErrorePagoPAResponse", targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp/types", partName = "parameters")
    @WebMethod(operationName = "TrasmettiFlussiInErrorePagoPA", action = "http://www.csi.it/epay/epaywso/RiconciliazioneVersamentiPSP/TrasmettiFlussiInErrorePagoPA")
    public it.csi.epay.epaywso.types.ResponseType trasmettiFlussiInErrorePagoPA(
        @WebParam(partName = "parameters", name = "TrasmettiFlussiInErrorePagoPARequest", targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp/types")
        it.csi.epay.epaywso.riconciliazione_versamenti_psp.types.TrasmettiFlussiInErrorePagoPARequest parameters
    );

    @WebResult(name = "EsitoFlussiPagoPAResponse", targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp/types", partName = "parameters")
    @WebMethod(operationName = "EsitoFlussiPagoPA", action = "http://www.csi.it/epay/epaywso/RiconciliazioneVersamentiPSP/EsitoFlussiPagoPA")
    public it.csi.epay.epaywso.riconciliazione_versamenti_psp.types.EsitoFlussiPagoPAResponse esitoFlussiPagoPA(
        @WebParam(partName = "parameters", name = "EsitoFlussiPagoPARequest", targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp/types")
        it.csi.epay.epaywso.riconciliazione_versamenti_psp.types.TestataTrasmissioneFlussiType parameters
    );

    @WebResult(name = "TrasmettiFlussiPagoPAResponse", targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp/types", partName = "parameters")
    @WebMethod(operationName = "TrasmettiFlussiPagoPA", action = "http://www.csi.it/epay/epaywso/RiconciliazioneVersamentiPSP/TrasmettiFlussiPagoPA")
    public it.csi.epay.epaywso.types.ResponseType trasmettiFlussiPagoPA(
        @WebParam(partName = "parameters", name = "TrasmettiFlussiPagoPARequest", targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp/types")
        it.csi.epay.epaywso.riconciliazione_versamenti_psp.types.TrasmettiFlussiPagoPARequest parameters
    );

    @WebResult(name = "RicercaProvvisoriPagoPAResponse", targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp/types", partName = "parameters")
    @WebMethod(operationName = "RicercaProvvisoriPagoPA", action = "http://www.csi.it/epay/epaywso/RiconciliazioneVersamentiPSP/RicercaProvvisoriPagoPA")
    public it.csi.epay.epaywso.riconciliazione_versamenti_psp.types.RicercaProvvisoriPagoPAResponse ricercaProvvisoriPagoPA(
        @WebParam(partName = "parameters", name = "RicercaProvvisoriPagoPARequest", targetNamespace = "http://www.csi.it/epay/epaywso/riconciliazione-versamenti-psp/types")
        it.csi.epay.epaywso.riconciliazione_versamenti_psp.types.RicercaProvvisoriPagoPARequest parameters
    );
}
